#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}


VER="128248/694464/version/1/file/ezpublish_community_project-2012.5-with_ezc.tar.gz"
URL="http://share.ez.no/content/download/$VER"

cd /usr/local/src
curl -L -f -O $URL

