#!/bin/sh -ex

DB_NAME=ezpublish
DB_USER=ezpublish
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/ezpublish

# tweak apache-credit
CONF=/etc/apache2/mods-available/substitute.conf
sed -i "s|</body>|</footer>|g" $CONF

# unpack and set permissions
tar -zxf $SRC/ezpublish_*.tar.gz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/ezpublish_* $WEBROOT
rm $SRC/ezpublish_*.tar.gz

chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/var
chown -R www-data:www-data $WEBROOT/design
chown -R www-data:www-data $WEBROOT/settings
chown -R www-data:www-data $WEBROOT/extension

# php.ini tweaks
PHPINI=/etc/php5/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 64M|" $PHPINI
sed -i "s|^;date.timezone.*|date.timezone = \"America/Los_Angeles\"|" $PHPINI

# configure apache
a2dissite default
a2ensite ezpublish
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

