#!/bin/sh -ex

DB_NAME=ezpublish
DB_USER=ezpublish
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/ezpublish

# tweak apache-credit
CONF=/etc/apache2/mods-available/substitute.conf
sed -i "s|</body>|</footer>|g" $CONF

# unpack and set permissions
tar -zxf $SRC/ezpublish_*.tar.gz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/ezpublish_* $WEBROOT
rm $SRC/ezpublish_*.tar.gz

chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/var
chown -R www-data:www-data $WEBROOT/design
chown -R www-data:www-data $WEBROOT/settings
chown -R www-data:www-data $WEBROOT/extension

